from app.models.base import Base
from app.models.user import User
from app.models.fakultas import Fakultas
from app.models.program_studi import ProgramStudi
from app.models.mahasiswa import Mahasiswa
from app.models.kurikulum_version import KurikulumVersion
from app.models.cpl import CPL
from app.models.ik import IK
from app.models.mata_kuliah import MataKuliah
from app.models.pengampu_mata_kuliah import PengampuMataKuliah
from app.models.cpmk import CPMK
from app.models.cpmk_ik_map import CPMKIKMap
from app.models.jenis_evaluasi import JenisEvaluasi
from app.models.bentuk_penilaian import BentukPenilaian
from app.models.mk_bentuk_penilaian import MKBentukPenilaian
from app.models.mk_bentuk_penilaian_ik_map import MKBentukPenilaianIKMap
from app.models.peserta_mata_kuliah import PesertaMataKuliah
from app.models.nilai_bentuk_penilaian import NilaiBentukPenilaian
from app.models.ik_achievement import IKAchievement
from app.models.cpl_achievement import CPLAchievement
from app.models.cpmk_achievement import CPMKAchievement
from app.models.hasil_evaluasi import HasilEvaluasi
from app.models.rps import RPS
from app.models.narasi_evaluasi import NarasiEvaluasi
from app.models.laporan_evaluasi import LaporanEvaluasi
from app.models.siap_sync_log import SiapSyncLog