from app.models.base import Base
from app.models.user import User
from app.models.program_studi import ProgramStudi
from app.models.mata_kuliah import MataKuliah
from app.models.mahasiswa import Mahasiswa
from app.models.cpl import CPL
from app.models.cpmk import CPMK
from app.models.penilaian import Penilaian
from app.models.hasil_prediksi import HasilPrediksi
from app.models.rekomendasi_llm import RekomendasiLLM
